name: Run Tests

on:
  push:
    branches: ['main']

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-patg: '**/package-lock.json'

      - run: npm ci

      - name: Run Test
        uses: actions/checkout@v2
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DATABASE_CLIENT: ${{ secrets.DATABASE_CLIENT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PORT: ${{ secrets.PORT }}